openapi: '3.0.2'
info:
    title: MagicWare API
    version: 1.0.0
    description:    |
        Informations about general MagicWare API.
        # Getting Started
        ## Security
        ### HTTPS
        All api calls and callbacks require HTTPS. Your service will need a valid SSL certificate and be accesible via the standard SSL port (port 443).
        ## Making an API request
        ```POST https://magicware.iscontent.cz/api/v1/reservations/businessCases HTTP/1.1```
        ```json
        {
            Accept: text/json
            X-API-Authentication-Token: e00a713d-ad81-4b4f-8801-31b34842f640
            Content-Type: application/json; charset=utf-8
            Content-Length: 1000
        }
        ```
    x-logo:
        url: "https://avatars1.githubusercontent.com/u/8859303"
externalDocs:
    url: 'http://www.magicware.cz'
    description: More information here.
servers:
    -    url: https://{instanceName}.{instanceUrl}.com/api/{apiVers}
         description: API server URL format
         variables:
             instanceName:
                 default: 'magicware'
                 description: Actual instance of M2G
             instanceUrl:
                 default: '#instanceUrl#'
                 description: Actual instance of M2G
             apiVers:
                 default: 'v1'
tags:
    -    name: Product
         description: Everything about products
         externalDocs:
             url: 'http://magicdoc/OpenKM/'
             description: Find out more about this topic
    -    name: Business case
         description: Everything about business cases
         externalDocs:
             url: 'http://magicdoc/OpenKM/'
             description: Find out more about this topic
paths:
    /products/priceCorrections:
        put:
            description:    |
                #instanceUrl#: is>content
                
                The price correction currently affects adjusted product variant prices only in exports.
            responses:
                '200':
                    description:    |
                        OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/priceCorrection'
                '401':
                    description:    |
                        Authorization token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/responses/401NotAuthorized'
            tags:
                -    Product
            summary: 'Allows to re-price product variants or adjust their end price.'
            security:
                -    ApiKeyAuth: []
            requestBody:
                required: True
                description:    |
                    Price correction with it's type how it behave and it's variant unique key.
                    To remove the price correction, just simply set the price correction amount to a zero.
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/priceCorrection'
    /reservations/businessCases:
        post:
            description:    |
                #instanceUrl#: is>content
                
                Creates new business case. Returns extra ID and Number of created business case.
            tags:
                -    Business case
            summary: 'Allows to create a new business case.'
            security:
                -    ApiKeyAuth: []
            requestBody:
                required: True
                description:    |
                    Defines the business case.
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/businessCase~1request'
            responses:
                '200':
                    description:    |
                        OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/businessCase~1response'
                '401':
                    description:    |
                        Authorization token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/responses/401NotAuthorized'
    /reservations/businessCases/bcCustomInfo:
        put:
            description:    |
                #instanceUrl#: is>content
                
                Requires existing business case.
            tags:
                -    Business case
            summary: 'Allows to actualize additional data of a business case.'
            security:
                -    ApiKeyAuth: []
            requestBody:
                required: True
                description:    |
                    Defines additional data for a business case.
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/bcCustomInfo'
            responses:
                '200':
                    description:    |
                        OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/bcCustomInfo'
                '401':
                    description:    |
                        Authorization token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/responses/401NotAuthorized'

                                      
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Authentication-Token
      description: "<p>All api calls require an Authorization Key which will be provided by M2G api login request.<p><p>The key needs to be provided in the header as follows: </p><p><b>X-API-Authentication-Token: {Your-Key-Here}</b></p>The key is not case sensitive."
  schemas:
    priceCorrection:
      type: object
      required:
        - amount
        - correctionType
        - dateFrom
        - nights
        - productId
        - facilityUnitPlanId
      properties:
        amount:
          type: number
          format: double
          description: The value of a price correction
        correctionType:
          type: string
          description: |
            Type of correction amount and how it's gonna behave with price
              - "correctionAmount": apply price correction on the price as adding the amount to the price.<br />
              - "newPrice": apply price correction on the price as switching the price with the price correction amount.
          enum:
            - correctionAmount
            - newPrice
        dateFrom:
          type: string
          format: date
          description: Date From
        nights:
          type: integer
          format: int32
          description: Count of nights
        departureTransportFacilityId:
          type: integer
          format: int32
          description: ID of a depature transport facility
          nullable: true
        departureStationId:
          type: integer
          format: int32
          description: ID of a departure station
          nullable: true
        returnArrivalStationId:
          type: integer
          format: int32
          description: ID of an arrival station
          nullable: true
        productId:
          type: integer
          format: int32
          description: ID of a product
        priceListCategoryCbId:
          type: integer
          format: int32
          description: Codebook ID of a price list category
          nullable: true
        boardTypeCbId:
          type: integer
          format: int32
          description: Codebook ID of a board type
          nullable: true
        saleGroupId:
          type: integer
          format: int32
          description: ID of a sale group
          nullable: true
        facilityUnitPlanId:
          type: integer
          format: int32
          description: ID of a facility unit plan
    businessCase/request:
      type: object
      properties:
        name:
          type: string
          description: Project name
          nullable: true
        customerId:
          type: integer
          format: int32
          description: ID of a customer.
          nullable: true
        businessCaseKindCbId:
          type: integer
          format: int32
          description: ID of a business case kind.
          nullable: true
        costCenterId:
          type: integer
          format: int32
          description: ID of a cost center.
          nullable: true
    businessCase/response:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: ID of new business case
        number:
          type: number
          format: double
          description: Number of new business case
        name:
          type: string
          description: Project name
          nullable: true
        customerId:
          type: integer
          format: int32
          description: ID of a customer.
          nullable: true
        businessCaseKindCbId:
          type: integer
          format: int32
          description: ID of a business case kind.
          nullable: true
        costCenterId:
          type: integer
          format: int32
          description: ID of a cost center.
          nullable: true
    bcCustomInfo:
      type: object
      required:
        - businessCaseId
      properties:
        businessCaseId:
          type: integer
          format: int32
          description: ID of the business case that additional data are for
        destinationId:
          type: integer
          format: int32
          description: ID of a destination
          nullable: true
        productTypeId:
          type: integer
          format: int32
          description: ID of a product type
          nullable: true
        accommodationCategoryCbId:
          type: integer
          format: int32
          description: ID of an accommodation
          nullable: true
        boardTypeCbId:
          type: integer
          format: int32
          description: ID of a board
          nullable: true
        transportTypeCbID:
          type: integer
          format: int32
          description: ID of a board
          nullable: true
        term:
          $ref: '#/components/schemas/bcCustomInfo~1Term'
        accommodationTerm:
          $ref: '#/components/schemas/bcCustomInfo~1AccommodationTerm'
        hotelName:
          type: string
          description: Name of a hotel
        roomKind:
          type: string
          description: Kind of a room
        departurePlace:
          type: string
          description: Departure place
        services:
          type: string
          description: Additional services
    bcCustomInfo/Term:
      description: Term of accomodation
      type: object
      properties:
        dateFrom:
          type: string
          format: date
          description: Date from
          nullable: true
        dateTo:
          type: string
          format: date
          description: Date to
          nullable: true
    bcCustomInfo/AccommodationTerm:
      description: Start and end of the trip
      type: object
      properties:
        dateFrom:
          type: string
          format: date
          description: Date from
          nullable: true
        dateTo:
          type: string
          format: date
          description: Date to
          nullable: true
  responses:
    401NotAuthorized:
      description: Authorization token is missing or invalid

